### ISSUE TITLE
USER STORY: Register position and add information about the location

### ISSUE THREAD

**Issue by peanutbutterclassic** [peanutbutterclassic/tack#2]
### User Story
As an **environmental consultant**, I can **position where I am, tag a photo, and add relevant environmental information about the place I visited** so that **I can create a record of the place I have visited, and have information as data to be used for further environmental analysis**

## Acceptance Criteria:
- Environmental consultant is able to use geolocation to accurately position where he/she is
- Environmental consultant is able to upload a photo(s) to the position registered
- Environmental consultant is able to add environmental information such as type of species observed or environmental issues identified to the location registered

## Tasks:
- [ ] Use google map as an interface through API to allow geolocation of data to be registered
- [ ] Add photo registration feature to google map 
- [ ] Create a form to be filled in by an environmental consultant.
